# Generated by Django 3.2.5 on 2021-07-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeapp', '0002_alter_mode_messege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mode',
            name='messege',
        ),
        migrations.AddField(
            model_name='mode',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
